api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

#    change the name of the ordering parameter globally
#    collection:
#        order_parameter_name: '_order'
