api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

    collection:
#        order_parameter_name: '_order' change the name of the ordering parameter globally
        pagination:
#            enabled: false
            page_parameter_name: _page
#            client_enabled: true
#            enabled_parameter_name: pagination
#            items_per_page: 4
            items_per_page: 10
            client_items_per_page: true # disabled by default
            items_per_page_parameter_name: itemsPerPage
            maximum_items_per_page: 20
            partial: false # only shows the next page of items
            client_partial: true
            partial_parameter_name: 'partial'
    exception_to_status:
        App\Exception\EmptyBodyException: 400

